# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: IThundxr
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_gists: no
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_skipped: dotfiles
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%
          plugin_people: no
          plugin_projects: no
          plugin_stars: no

